config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :users, only: %i[new create]

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  get 'welcome', to: 'sessions#welcome'
  post 'logout', to: 'sessions#destroy'

  get 'static/home'
  get 'static/deposit'
  get 'static/withdraw'
  get 'static/transfer'

  resources :accounts, only: %i[show create update destroy]

  root 'static#home'
end

app/models/account.rb
# frozen_string_literal: true

class Account < ApplicationRecord
  validate :balance_cannot_be_negative

  has_many :transactions

  def update(params)
    deposit(params[:deposit_value].to_f) unless params[:deposit_value].nil?
    withdraw(params[:withdraw_value].to_f) unless params[:withdraw_value].nil?
    unless params[:transfer_value].nil? && params[:dest_account].nil?
      transfer_out(params[:transfer_value].to_f,
                   Account.find(params[:dest_account].to_f))
    end
  end

  def give_money(value)
    self.balance = balance + value if active
  end

  def take_money(value)
    self.balance = balance - value if active
  end

  def withdraw(value, kind = 'withdraw')
    take_money(value)
    transactions.create(value:, kind:) if valid?
  end

  def deposit(value, kind = 'deposit')
    give_money(value)
    transactions.create(value:, kind:) if valid?
  end

  def transfer_out(value, destination_account)
    withdraw(value, 'transfer')
    transactions[transactions.count - 1].collect_fees
    destination_account.deposit(value, 'transfer') if valid?
    destination_account.save
  end

  def historic_statement(initial_date, end_date)
    transactions.where(created_at: Date.parse(initial_date)..(Date.parse(end_date) + 1.day))
  end

  def balance_cannot_be_negative
    errors.add(:balance, " can't be negative") if balance.negative?
  end

  def value_cannot_be_empty(value)
    errors.add(:value, " can't be empty") if value.empty?
    value.empty?
  end

  def dest_account_cannot_be_empty(value)
    errors.add(:destination_account, " can't be empty") if value.empty?
    value.empty?
  end
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/transaction.rb
# frozen_string_literal: true

class Transaction < ApplicationRecord
  belongs_to :account

  validates :value, numericality: { greater_than: 0 }
  validates :fees, numericality: { greater_than_or_equal_to: 0 }
  validates :kind, inclusion: { in: %w[withdraw deposit transfer fee],
                                message: '%<value>s is not a valid kind of transaction' }

  before_validation do
    self.fees = 0 if fees.nil?
  end

  def banking_hours?
    return false if created_at.saturday? || created_at.sunday?

    created_at.hour.between?(9, 18)
  end

  def over_1000?
    value >= 1000
  end

  def calculate_fees
    self.fees = 7
    self.fees = 5 if banking_hours?
    self.fees += 10 if over_1000?
  end

  def collect_fees
    calculate_fees
    account.withdraw(self.fees, 'fee')
  end

  def transaction_date
    "#{created_at.day}/#{created_at.month}/#{created_at.year}"
  end
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  validates :username, presence: true

  has_secure_password

  has_many :accounts
end

app/controllers/accounts_controller.rb
# frozen_string_literal: true

class AccountsController < ApplicationController
  before_action :set_account, only: %i[show edit update destroy]

  def show; end

  def create
    @account = current_user.accounts.new

    redirect_to account_url(@account) if @account.save
  end

  def update
    @account.update(account_params)

    if @account.save
      redirect_to account_url(@account)
    else
      render :show, status: :unprocessable_entity
    end
  end

  def destroy
    @account.active = false

    if @account.save
      redirect_to welcome_path
    else
      render :show, status: :unprocessable_entity
    end
  end

  private

  def set_account
    @account = current_user.accounts.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    flash[:notice] = 'Acesso negado'
    redirect_to root_path
  end

  def account_params
    params.require(:account).permit(:withdraw_value, :deposit_value, :transfer_value, :dest_account)
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  helper_method :current_user
  helper_method :logged_in?
  before_action :authorized

  def current_user
    User.find_by(id: session[:user_id])
  end

  def logged_in?
    !current_user.nil?
  end

  def authorized
    redirect_to root_path unless logged_in?
  end
end

app/controllers/sessions_controller.rb
# frozen_string_literal: true

class SessionsController < ApplicationController
  skip_before_action :authorized, only: %i[new create welcome]

  def new; end

  def create
    @user = User.find_by(username: params[:username])

    if @user&.authenticate(params[:password])
      session[:user_id] = @user.id
      redirect_to '/welcome'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def login; end

  def welcome
    @accounts = current_user.accounts
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end
end

app/controllers/static_controller.rb
# frozen_string_literal: true

class StaticController < ApplicationController
  before_action :set_account, only: %i[deposit withdraw transfer]
  before_action :redirect_to_welcome, only: :home
  skip_before_action :authorized, only: :home

  def home; end

  def deposit; end

  def withdraw; end

  def transfer; end

  private

  def set_account
    @account = Account.find(params[:account])
  end

  def redirect_to_welcome
    redirect_to '/welcome' if logged_in?
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  skip_before_action :authorized, only: %i[new create]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      session[:user_id] = @user.id
      redirect_to '/welcome'
    else
      render :new, status: :unprocessable_entity
    end
  end
end

private

def user_params
  params.require(:user).permit(:username, :password)
end

app/helpers/accounts_helper.rb
# frozen_string_literal: true

module AccountsHelper
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/sessions_helper.rb
# frozen_string_literal: true

module SessionsHelper
end

app/helpers/static_helper.rb
# frozen_string_literal: true

module StaticHelper
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
end

app/views/accounts/index.html.erb
<h1>Accounts#index</h1>
<% @accounts.each do |account| %>
	
	<%= link_to(account) do%>
		<p>Account # <%= account.id %></p>
	<% end %>

<% end %>

<%= button_to "Abrir uma conta",accounts_path, method: :post %>

app/views/accounts/show.html.erb
<div class="account-info">
	<div class="account-status">
		<h1>Conta #<%= @account.id %></h1>
		<p><%= @account.active ? "ATIVA" : "INATIVA"%></p>
	</div>
	
	<p class="saldo">
		Saldo atual: </br>
		R$ <%= @account.balance %>
	</p>
	
	<h1>Extrato</h1>

	<div class="statement">

		<div class="statement-header">
			<p>Data</p>
			<p>Tipo</p>
			<p>Valor</p>
		</div>
		<% @account.transactions.each do |transaction|%>
			<div class="statement-line">
				<p><%= transaction.transaction_date %></p>
				<p><%= transaction.kind %></p>
				<p><%= transaction.value %></p>
			</div>
		<% end %>

	</div>	
</div>

<% content_for :right_pane do %>
	<% if @account.active %>
		<%= link_to "Depositar", static_deposit_path(:account => @account) %>  
		<%= link_to "Sacar", static_withdraw_path(:account => @account) %> 
		<%= link_to "Transferir", static_transfer_path(:account => @account) %>
		<%= button_to "Desativar conta", @account, method: :delete %>
	<% else %>
		<p> CONTA INATIVADA </p>		
	<% end %>	
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Caixa de auto-atendimento</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Bebas+Neue&display=swap" rel="stylesheet">
  </head>

  <body>
    <div class="main-cont">
      
      <div class="header">
        <%= button_to "Home",root_path, method: :get %>
        <h1>Caixa de Atendimento</h1>
        <% if logged_in?%>
          <%= button_to "Sair",logout_path, method: :post %>
        <% end %>
      </div>

      <p><%= notice %></p>
    
    <div class="main-console">
      <div class="left-pane">
        <%= yield %>
      </div>
      <div class="right-pane">
        <%= yield :right_pane%>
      </div>
    </div>

    </div>
  </body>
</html>

app/views/users/new.html.erb
<h1>Cadastre-se:</h1>


  <% if @user.errors.any? %>
  <div class="errors">
      <h2>Os seguintes erros foram encontrados:</h2>
      <% @user.errors.each do |error|%>
        <p><%= error.full_message %></p>
      <% end %>
  </div>
  <% end %>


<%= form_for(@user) do |form|%>
  <%= form.label :username, "Seu nome:"%>
  <%= form.text_field :username%>
  <%= form.label :password, "Sua senha:"%>
  <%= form.password_field :password%>
  <%= form.submit 'Concluir cadastro' %>
<%end%>

<% content_for :right_pane do %>
  <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec nulla lectus, vestibulum in faucibus at, eleifend et turpis. Praesent maximus urna id quam auctor, id consequat risus hendrerit. Nullam in condimentum nisi, at ornare dui. Nulla non convallis metus. Nam molestie euismod vulputate. Etiam molestie sed eros vel euismod. Pellentesque fermentum lorem at diam placerat, quis consectetur diam vestibulum. Pellentesque nisi ex, commodo at metus in, malesuada vulputate orci. Mauris porttitor eros sed lacus vehicula, et semper turpis tincidunt.</p>
<% end %>